/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_atalk_impl_neomedia_codec_video_VPX_StreamInfo */

#ifndef _Included_StreamInfo
#define _Included_StreamInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
