/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_atalk_impl_neomedia_transform_srtp_OpenSSLWrapperLoader */

#ifndef _Included_org_atalk_impl_neomedia_transform_srtp_OpenSSLWrapperLoader
#define _Included_org_atalk_impl_neomedia_transform_srtp_OpenSSLWrapperLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_atalk_impl_neomedia_transform_srtp_OpenSSLWrapperLoader
 * Method:    OpenSSL_Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_atalk_impl_neomedia_transform_srtp_OpenSSLWrapperLoader_OpenSSL_1Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
