#!/bin/bash
# set -x
pkg_name=${@: -1}

SCRIPT=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT")
#export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig
case $1 in
  --exists)
    pkg-config --exists $pkg_name
    ;;
  --cflags)
    echo $(pkg-config --cflags $pkg_name)
    ;;
  --libs)
    echo $(pkg-config --libs $pkg_name)
    ;;
  *)
    echo "FFmpeg pkg-config to build FFmpeg for Android!"
    ;;
esac
